### ISSUE TITLE
Alarm 需要可以自定义规则对发出的报警做变换

### ISSUE THREAD

**Issue by feisuzhu** [leancloud/satori#24]
针对每个
- 报警组
- 个人

可以做
- 对报警内容做修改（比如，报警级别）
- 丢弃

```yaml
users:
  proton:
    name: Proton
    email: bwang@leancloud.rocks
    filters:
      - filter: good_night  # 夜晚时间段 1 级以下的报警不要通知我
        mute_at: 0:00 - 8:00
        mute_below_level: 1  
      - filter: threshold  # 至少是 3 级报警才通知我
        level: 3
```

filters 需要放在规则仓库内，随时可以做自定义
